---
title: "p8105_hw5_rl3616"
author: "Ruipeng Li"
date: "`r format(Sys.Date())`"
output: github_document
---
```{r}
library(tidyverse)
library(broom)
```


```{r data clean}
homicides <- read.csv("data/homicide-data.csv")

homicides_df <- homicides |> 
  janitor::clean_names() |>
  mutate(
    city_state = str_c(city, ", ", state),
    resolved = ifelse(disposition == "Closed by arrest", 1, 0),
    victim_age = str_trim(victim_age),
    victim_age = na_if(victim_age, "Unknown"),
    victim_age = parse_number(victim_age)
  ) |> 
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),
    victim_race %in% c("White", "Black")
    )

```

```{r for baltimore}
baltimore_mod <- homicides_df |>
  filter(city_state == "Baltimore, MD")

baltimore_mod <- glm(
  resolved ~ victim_age + victim_sex + victim_race,
  data = homicides_df,
  family = binomial
)

broom::tidy(baltimore_mod, exponentiate = TRUE, conf.int = TRUE) |> 
  filter(term == "victim_sexMale")
```

```{r for all city}
city_results <- homicides_df |>
  group_by(city_state) |>
  nest() |>
  mutate(
    model = map(data, ~ glm(
      resolved ~ victim_age + victim_sex + victim_race,
      data = .x,
      family = binomial
    )),
    tidy = map(model, ~ tidy(.x, exponentiate = TRUE, conf.int = TRUE))
  ) |>
  unnest(tidy) |>
  filter(term == "victim_sexMale")
```